### ISSUE TITLE
Cyrillic support

### ISSUE THREAD

**Issue by ksk-waqs** [aCluelessDanny/typora-theme-ursine#10]
Hello, please implement support for the Cyrillic alphabet. Now the Russian text looks weird.

**Comment by aCluelessDanny** [comment]
Ah that should be easy. It's more of a font issue since 2 of the 3 fonts the theme is using don't have the Cyrillic alphabet symbols. Fortunately after a quick Google search, it looks like they both have Cyrillic-compatible variants, so it's just a matter of swapping the files (and hopefully nothing else, since I've never really handled Cyrillic writing before). Shouldn't take me too long to do.

Can you do me a favor though (if your computer's system language is set to Russian)? Can you enable debugging (`Preferences -> Enable debug`), open the developer tools (right click anywhere on the writing area and select `Inspect Element`), and show me the `html` tag attributes?
<img width="364" alt="image" src="https://user-images.githubusercontent.com/21282515/56783134-c4c9ad80-67af-11e9-8f36-bf5df325e728.png">

I want to migrate to Sass afterwards to help modularize the files, & this information might help me out a bit later on. I tried to tinker with it myself, but I don't know if I'm having troubles since my computer's language is set to English.

**Comment by aCluelessDanny** [comment]
The [release](https://github.com/aCluelessDanny/typora-theme-ursine/releases/tag/1.5.1) is up now~. Make sure to pick the zip that says Cyrillic!
