### ISSUE TITLE
Highlighter color

### ISSUE THREAD

**Issue by LeBaux** [aCluelessDanny/typora-theme-ursine#17]
![image](https://user-images.githubusercontent.com/5657511/59838888-0b6efa80-9350-11e9-9283-a6275eaddb05.png)

If you enable `Preference > Syntax Support > Highlight`, it is way too bright in Ursine Umbra. Please consider some darker shade of blue, since it is sore to eyes.

As a side note, Ursine works great under Linux, however at least Manjaro has slight issues with some glyphs, namely `y` as you can see from the screenshot. Not that you should do anything about it, just reporting the state of things.

Thank you for making the theme, it is truly great!

**Comment by aCluelessDanny** [comment]
Hey there, sorry it took a long while to hear back. I was out of town when this issue got posted, & I forgot to check back into this repo for a while after I got back.

I took into consideration the color of the background, and yeah, it's definitely a bit bright. I switched up the colors to fit the theme and be a bit more subtle but still able to distinguish the highlighted background (as well as change the other theme's `mark` color since I'm already at it). Hopefully I'll get a release out before today ends.

<img width="120" alt="image" src="https://user-images.githubusercontent.com/21282515/62259945-c1107d00-b3d5-11e9-8247-dd8514a70b2c.png">
<img width="110" alt="image" src="https://user-images.githubusercontent.com/21282515/62259964-e309ff80-b3d5-11e9-8cae-af2d52b0a925.png">
