### ISSUE TITLE
Expand/wrap text to window width instead of fixed width

### ISSUE THREAD

**Issue by coffee-and-genomics** [aCluelessDanny/typora-theme-ursine#25]
Can you implement functionality where the Ursine Polar/Umbra themes wrap to the width of the open window when the window is large rather than only expanding up to a certain width?

**Comment by aCluelessDanny** [comment]
(A bit late to this, sorry!)

I could do that by changing a couple of lines, but this is more of a design choice I wanted to keep from Bear. I personally kinda like that negative space when it comes to note-taking, & other people may like that part of it as well.

I could make another variant available in the releases page that has this, but I fear I'd just clutter each released version like this overtime, since it'd be just a duplicate with a couple of small changes. Not sure if that's the way to go or not, so I'll await a response.

For now though, you can get this by doing a small change to the file. In lines `300-305` in both Ursine Polar and Umbra's CSS files (`ursine-polar.css`/`ursine-umbra.css`), you'll find this block of code:

```css
#write {
  position: static;
  width: 90%;
  max-width: 700px;
  line-height: 1.6;
  transform: none;
}

```

Simply delete the line that has `max-width`, & that'll do the trick. You can also play around with the percent value of `width` if you want to increase or decrease the writing area width.

**Comment by coffee-and-genomics** [comment]
That manual workaround works just fine. I just commented it out instead of deleting it. Thank you!
