### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by TerickJojo** [aCluelessDanny/typora-theme-ursine#28]
Please keep the background image while we do the document.

**Comment by aCluelessDanny** [comment]
Hey there!

Just like with #25, this is more of a design choice to mimic Bear's way of handling this part, as in Bear, the "splashscreen" disappears when a file opens (or in this case, when the writing area is no longer empty).

Though this one actually poses a problem because of how it's implemented, since I had to be a bit hacky in order for the CSS to detect if nothing had been typed yet. If I were to make it always visible, #13 will reoccur & selecting text would look kinda finicky. I can implement this in another way to always display the splashscreen with (hopefully) no issue, but again, some people may like it to just appear when there's no text.

I did suggest making "variant" releases with small changes, but I refrain from that since I'd clutter every release version with every combination of each variant's changes. Maybe I can make a script to be run by the user to customize the CSS files with things like these, but that may be a while if the demand is there.
