### ISSUE TITLE
Always show clear table header in focus mode

### ISSUE THREAD

**Issue by krokofant** [aCluelessDanny/typora-theme-ursine#32]
Would it be an improvement to make the table header more visible when in focus mode?

![image](https://user-images.githubusercontent.com/5908498/63152539-651c3a00-c00c-11e9-99d0-2a13398b80ec.png)

Consider that the data lines above and below are not especially important but knowing what data goes in which column is.

Alternatively highlight the header of the column you're currently in. So in the image above it would highlight only the "Foo" column.

**Comment by aCluelessDanny** [comment]
_(Late again, though this time I've been left without a computer for over a week so far due to repairs, & I'm hoping to get it within the next few days. Sorry 'bout that)_

Highlighting the current column can be pretty helpful. It's basically the same as highlighting the current header, just with every other element in the column, & it shows relevant information (and hopefully it's not too distracting). I just have to see if Typora allows me to do that with a CSS class of sorts; so I'll keep ya posted once I get my computer back

**Comment by krokofant** [comment]
I didn't find any css classes which could be targeted. I created an issue on the typora issue tracker.

**Comment by aCluelessDanny** [comment]
Yeah, looks like without the right CSS class, we're gonna have to wait for that functionality. Gonna close this until then
