### ISSUE TITLE
The Highlighter Color

### ISSUE THREAD

**Issue by danielduyixin** [aCluelessDanny/typora-theme-ursine#34]
The highlight color I saw on your website is green，but on my PC it becomes pink?Why is that ?See the picture.
![1](https://user-images.githubusercontent.com/19722567/63849232-3ca91e00-c9c4-11e9-8ad3-e67bdc065f28.png)
![2](https://user-images.githubusercontent.com/19722567/63849235-3dda4b00-c9c4-11e9-96d4-edbef2507e5f.png)
I like your theme very much, it is like Bear on IOS,thank you.

**Comment by aCluelessDanny** [comment]
Ah yes! I recently changed the highlighter color for both themes in [1.6.3](https://github.com/aCluelessDanny/typora-theme-ursine/releases/tag/1.6.3), I just haven't updated the screenshots in the README yet, ahah. But that is the intended color (though I might change them again since I think the color could stand out a bit more as a highlighter).

And thank you, glad you like it!

**Comment by danielduyixin** [comment]
Sorry but i don’t like the new color ,how can i change it back?😂 

发自我的iPhone
