### ISSUE TITLE
Ordered list will always be reset to 1, and cannot start from arbitrary number

### ISSUE THREAD

**Issue by Michael-Zhang-07** [aCluelessDanny/typora-theme-ursine#4]
Hi,
Thank you so much for your contribution of this theme, I enjoy it a lot than any other themes. There is only one issue that I am really concerned, I tried to fixed it by myself but failed. Unlike other themes, the numbered list will automatically reset to 1 if it is the first one, regardless of which number you typed it. Suppose I put `2.` or anything else, the actual view will turn to `1.` and begin to count from 1. (Windows)

I am not sure if this is your special design, it can be quit convenient for some unexpected typos though and always correct the numbers. But sometimes I want to get it start from a specific number, or write something without indent and then follow the number flow by hand.

I would be grateful if you can fix this, or maybe just show me a little how to solve this if this is indeed your special design. This theme is almost all I want, and I really want to figure this small problem.

Thank you.

**Comment by aCluelessDanny** [comment]
Ah, as I read this, I knew exactly what's causing that. Thing is I made a custom _psuedo-element_ that'd replace the native one because I didn't know how to style it at the time, but I forgot about that limitation (it'd reset its "counter" every time a new list was made). I took that off and found a way to style the original numbering, so it should be working now (the code's cleaner this way too, I probably over-complicated that part 💦 )

I just pushed this into the `dev` branch, though I should be able to put out a new release with a couple of other changes by tonight or tomorrow
<img width="91" alt="image" src="https://user-images.githubusercontent.com/21282515/54485292-a4ffab00-483b-11e9-9b1d-21fbdf48f4cf.png">

**Comment by aCluelessDanny** [comment]
And [there we go!](https://github.com/aCluelessDanny/typora-theme-ursine/releases/tag/1.3). Give it a try and see if it's working for ya now

**Comment by Michael-Zhang-07** [comment]
Amazing! Thank you so much!!! This becomes perfect for me! 👍
