### ISSUE TITLE
Greek fonts look weird

### ISSUE THREAD

**Issue by spirosag** [aCluelessDanny/typora-theme-ursine#45]
Hi,
Unfortunately greek fonts look very weird, with wonky letters. I tried both the cyrillic and the regular version.
If you plan on fixing them I can give you screenshots of what's wrong just tell me!

Thanks for a great theme!
👍👍👍

**Comment by aCluelessDanny** [comment]
Ah, please do! It could be the font not supporting it, but it's best if I can see what looks funny about it.

I actually forgot about up pushing some fixes for a while, so now's a good time to see if I can add one more in there before another release.

**Comment by spirosag** [comment]
![2020-01-13 10_02_19-Untitled• - Typora](https://user-images.githubusercontent.com/621378/72240301-5bfbbd00-35ec-11ea-8457-6ebff78a33f8.png)

As you can see there is quite the difference between the greek and the engllish font. Also some greek words (like π, μ) appear like they are in a different font.
This is with the regular theme not the cyrillic.

Tell me if you need more.

**Comment by aCluelessDanny** [comment]
Yeah, it's what I thought, both fonts are *mostly* incompatible with Greek in general. A few of those words (like the π & μ that you mentioned) happened to be compatible since they have a few uses in other languages.

Probably the best thing to do is to make a "Greek" release pack with fonts that are compatible with the language. I did some digging to find fonts that are compatible and similar enough to the ones the theme uses, so mind if you can check if these are good (and also try testing them in the site just in case, haha)?

Headers would use the [Roboto Slab](https://fonts.google.com/specimen/Roboto+Slab) font and paragraphs would use the [Open Sans](https://fonts.google.com/specimen/Open+Sans) one. The monospace/code font should still be good to use here

**Comment by spirosag** [comment]
I think they would work. 👍 I tested them a bit with some greek text that was looking weird previously. 
If you release such a greek release let me know and I'll  test it more.

**Comment by aCluelessDanny** [comment]
So a bit of fiddling later, and this is about as close as I can get to make the look similar while keeping it Greek-compatible.

The left shows the original font, while the right has the greek-safe ones (it also happens to also support Cyrillic and Vietnamese, so that's a bonus)

<img width="1475" alt="image" src="https://user-images.githubusercontent.com/21282515/72379440-09e49580-36d9-11ea-8779-98bf81e97347.png">

I'm gonna try to get the release out before dusk, so give it a try once that's up & tell me if it works out alright~

**Comment by spirosag** [comment]
I think it looks pretty good. With a quick look could'nt find anything wrong. I'll let you know if I stumble on any more incosistencies. Closing this and thanks again! 🙏🔥🤟
