### ISSUE TITLE
This is not a issue, but a suggestion

### ISSUE THREAD

**Issue by sugry** [aCluelessDanny/typora-theme-ursine#49]
Hi! I apologize if I posted it in the wrong place.
I did some experiments based on your design theme and I liked the result. I want to share this. If you like my ideas, please use them in your design theme or in a new one.
I am attaching a [screenshot](https://imgur.com/AK33GPI), a [link to a theme file](https://mega.nz/#!zgNgTapK!rqw1P56smO1GdS54R_JMc6NHIp3ooe9M2l40Yjqfw-Y), and a [link to a test file](https://mega.nz/#!v58lTQ4J!jfkTwTX8c4nWjzX6n7lUpWAVJ6ZkLD5RnfHLhzPR8bE).
I will be glad if Typora will add good themes.

**Comment by aCluelessDanny** [comment]
Pardon the late reply, things got a little busy over on my side 💦

I like a lot of these choices actually! So I can go ahead and implement these with small tweaks here and there. There are a couple things I wouldn't include right away though:
- The header changes are pretty good, though some people might not prefer the counter. I also really like Bear's approach since it's rather minimalist. The dimmed backgrounds might be something I can consider, though I'll need to test how it looks on Polar.
- Changing the highlight text color to black _might_ be counter-intuitive, though I think I can tweak the background color a bit to have it stand out more.

**Comment by aCluelessDanny** [comment]
The 2.0 release now has a good chunk of these suggestions, so I'll go ahead and close this for now. Thanks for your contribution!
