### ISSUE TITLE
Exporting PDF formatting problem

### ISSUE THREAD

**Issue by mike-lowski** [aCluelessDanny/typora-theme-ursine#66]
Hi,

When you export your notes to PDF, if you used bold formatting inside a list, you lose it. Like for some reason cannot combine being in a list and being in bold formatting.

Another thing, not sure if a bug because haven't tried exporting to PDF with Bear, but the H1/H2/etc. codes are exported too in the PDF. Kinda pointless to have that info there.

Great theme, thanks for the work you are doing.

**Comment by aCluelessDanny** [comment]
Pardon the late reply. It looks like that's a hiccup of mine there, so it's a quick fix in this case. Also the H1, H2, ... tags are actually intentional since I think some might like having those indicators there in the export (I don't know how PDF exports work in Bear since that's a premium thing, but I imagine they keep it too).

And merci~. I should be able to get a hotfix release out later today

**Comment by aCluelessDanny** [comment]
There we go, should be good to go in the latest release now~
